name: Actualizar Lista IPTV
on:
  schedule:
    - cron: '33 * * * *' # Se ejecuta cada día a medianoche
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: pip install requests

      - name: Ejecutar script
        run: python tu_script.py # Cambia esto por el nombre de tu archivo .py

      - name: Subir cambios
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add lista2.m3u
          git commit -m "Lista actualizada automáticamente" || exit 0
          git push
